version: '3.8'
services:
  sec-service:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: sec-service
    ports:
      - "8888:8081"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306 
      - MYSQL_DB=sec_service_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
    
    networks:
      - reseau_gestion_paie
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '9025:25'
    networks:
      - reseau_gestion_paie  


networks:
  reseau_gestion_paie:
    external: true
    name: reseau_gestion_paie
    